services:

  # PostgreSQL database for Airflow metadata
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow        # DB username
      POSTGRES_PASSWORD: airflow    # DB password
      POSTGRES_DB: airflow          # metadata database name
    ports:
      - "5433:5432"                 # expose postgres to host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]  # check DB ready
      interval: 5s
      timeout: 5s
      retries: 10

  # Main Airflow service (webserver + scheduler)
  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor   # use local executor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"                # Airflow UI
    volumes:
      - ../../:/opt/airflow/repo   # mount project repo
      - ./dags:/opt/airflow/dags   # DAG directory
    command: bash -c "airflow webserver & airflow scheduler"

  # Initialization container
  # Runs once to migrate DB and create admin user
  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      # create admin login
      # create metadata tables
    command: >
      bash -c "airflow db migrate &&        
      airflow users create         
      --username admin
      --password admin
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@example.com"

      